#!/bin/bash

gradle -q clean build

if [ "$#" -ne 0 ]; then
    # Join arguments in a string. But not quite like you'd expect... see next line.
    printf -v var "'%s', " "$@"
    # Remove trailing ", "
    var=${var%??}
    gradle --stacktrace run -PappArgs="[$var]"
else
    gradle run
fi